# This is a basic workflow to help you get started with Actions

name: pullimagesTask

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

   

      # Runs a set of commands using the runners shell
      - name: Runner k8s.gci.io images
        run: |
          docker pull k8s.gcr.io/metrics-server/metrics-server:v0.6.2
          docker tag k8s.gcr.io/metrics-server/metrics-server:v0.6.2 registry.cn-beijing.aliyuncs.com/k8sjcrio/metrics-server:v0.6.2
      - name: login aliyun.image service & push image
        run: |
          docker login --username=${{ secrets,ALIYUNUSERNAME }} --password=${{ secrets,ALIYUNPASSWORD }} registry.cn-beijing.aliyuncs.com
          docker push registry.cn-beijing.aliyuncs.com/k8sjcrio/metrics-server:v0.6.2
      - name: push completions
        run: |
          echo "push image completion!!!"
       
